schema_version: 1

context:
  version: "1.610.0"

package:
  name: directx-headers
  version: ${{ version }}

source:
  url: https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 343b04a8206c4169a1feab99a7bd29ecb0c8f511988e9a007fea51768bda14fa

build:
  number: 1
  noarch: generic
  script:
    interpreter: brush
    content: |
      mkdir -p "${LIBRARY_INC:-$PREFIX/include}"
      cp -R include/directx include/wsl "${LIBRARY_INC:-$PREFIX/include}/"

requirements:
  build:
    - brush
    - uutils-coreutils
  run:
    - if: win
      then: __win
      else: __unix

tests:
  - package_contents:
      files:
        - if: win
          then:
            - Library/include/directx/d3d12.h
            - Library/include/directx/d3dx12.h
            - Library/include/directx/dxcore.h
          else:
            - include/directx/d3d12.h
            - include/directx/d3dx12.h
            - include/directx/dxcore.h

about:
  homepage: https://github.com/microsoft/DirectX-Headers
  repository: https://github.com/microsoft/DirectX-Headers
  summary: Official Direct3D 12 headers for Windows and Linux
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - baszalmstra
